[[SHTns]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "c127a4d5ae8d75db3cdb7fc9f0af5f6f797cbd31"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "5394668131a79c39f9efeb9587190319e1f1abb6ff27d91992bbd83a60c7d549"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "a1b7c922d969194448b6b9b5c89c066a1ca5a576"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "747d32885e836d0cd86ceb39732039748ef95f1ed10cfaa5129302089099b8f7"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "da9522899dd7f5b15acbdbdb1f290c94e35b8047"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "f782cce7b07f164d153a8235494da224cc996cff4e8823b876c29df0041b85f1"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "6062bb6a758577de4bad1bf4f6761ea01fa8848d"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "faf444fc60e2da178630adf26e53e9492addb0d3a7ddf3d9cff56f2e3d16fc79"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "d8cca712bc0d881b4e7ca4e18e2e5102a3c7f996"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "6cc78ee247b78398999987c4ae6cbdebac351b8d4a593b2063ee2ce7803973fb"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "288b2411bc65492ff952a790cd928c6d2cffc00a"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "875980ba4cb7e11aa9858864e3549c00775215e61396ac16b48e5c2a10ec617b"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "10f31a3e7e02ce224d27588073683931c5b152a5"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "a3693a3adba89253ad7843ceb222bf8bda96f1ae58402d79f8082a897e846ce8"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "6f93a38f4b3fdf06619f07803157965a30229b2b"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "4c29507b8256ad40a31c5d9e559b7dca1414e790f8ad7c6d5eee965226f732c5"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "4b2a1ccb51c434d06bd589400bc8151c335847d5"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "62a08cb509c3464634ded253c0d07ae5724ffdbd4d4297e05a0c53224c1985fa"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "578d7dec8e2dc8dac887231571d0a2bfda096597"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "10ac927eca61cd8c46658248a036760d215ecf568080c5db65afd0bde371709c"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "ffcc41cbe2007581425c4e27fb1c3ee331143ec0"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "cdb81e91f7a65e9645f66dad5fd38e715e720b04d07a71e616c9a25ef3edf821"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[SHTns]]
arch = "i686"
git-tree-sha1 = "3c6963b64cd37d81b4f0051a09cb48ed3464807c"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "ad7f8ab8436586461bdfd2a62e69d9595a05131dba055dbf561a7bd84fbe9f66"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.i686-linux-gnu.tar.gz"
[[SHTns]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "144f4290b5915999f8a7bc47e2333dbdcda6cdf0"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "2ffc587b8eddca82eecab3c21322d84759d83b7430f5cd88a58dcd2c118e6805"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-gnu-cuda+none.tar.gz"
[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "1cbde94729d833bcecbfc7f61ebbf648f647519d"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "9f99a947a51adda5384955f1a1257cc34870183a07eeafcf3b25c96a36fc293e"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.aarch64-linux-gnu.tar.gz"
[[SHTns]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "160aabee98bd324bd9969e17965a6e7091571ac0"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "1b17e4c00a6f27415d5c3b55efdfa62cd3a9e70293ec47bd00e2e9290561915a"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.armv6l-linux-gnueabihf.tar.gz"
[[SHTns]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a2e3dc7d047d49bb5085c37a8cf856d2d14b4de"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "889b70c880064ad77ed71fdc4c067144451109404bcc33d7558c9a1a10889ece"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.armv7l-linux-gnueabihf.tar.gz"
[[SHTns]]
arch = "powerpc64le"
git-tree-sha1 = "1e4c3429c1e35f5d270280abc86d72c69aca3b9c"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "ae29569e7e26eec780ea12111ba247f1f80280789feb4f12cd016437c2983ced"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.powerpc64le-linux-gnu.tar.gz"
[[SHTns]]
arch = "i686"
git-tree-sha1 = "5e814aa134b50937a7a18625f23cfa0869b5c511"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "272d795c577706daa25319d4933da2d0bbe1728eade2e2ee3ee81d60e7aaa24f"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.i686-linux-musl.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "68f9846af7e1309ea264a2cd80ee31eae83be30e"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "cbb9f11b26883dc51e6aff1f6c37398af2004c58c278e849ee7a55b754241dfe"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-linux-musl.tar.gz"
[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "c3e67dc64a19cb2c888d88aecd9af0fef8b53983"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "10e945a442356bebbbe78337a14a5c6c5413b91eff19111d3296dccecf9881b6"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.aarch64-linux-musl.tar.gz"
[[SHTns]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "17b370189edeb8e171d0b0d7336491b3b206ae9d"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "17e95d4595d33f01c0edf7f6d85b851f07012e3ac1437518e32010a782674744"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.armv6l-linux-musleabihf.tar.gz"
[[SHTns]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61b9d0dab7e513f2d7511dd33e95ec70c2901bfa"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "897a63a0d15c947eef11cd0562c47d6878042df266e105b71e704248672729f9"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.armv7l-linux-musleabihf.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "4d90f0216253455e5f48eb0f9064fb4be054b052"
lazy = true
os = "macos"

    [[SHTns.download]]
    sha256 = "c77c9e9106cbb3ab9bfcb83c34c521071dd4c2ab891dd792cb023f315c8900ac"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-apple-darwin.tar.gz"
[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "dc5f82af637ffdc033991aaf3bc1eae10541c5d4"
lazy = true
os = "macos"

    [[SHTns.download]]
    sha256 = "a4b7acc0552546aed10c0b3b90196772ed4ad0c067b93bb72a39da564f4892f1"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.aarch64-apple-darwin.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "5e35a26738765b85d65f1988b8d8acde8ecab405"
lazy = true
os = "freebsd"

    [[SHTns.download]]
    sha256 = "1ade13f59b42e49e738a164954563a5bf6ef19076e854dea81cc5bda135463f0"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-unknown-freebsd.tar.gz"
[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "bec917b43b36902bda3102c6772e4a1382e6450a"
lazy = true
os = "freebsd"

    [[SHTns.download]]
    sha256 = "d1fb85f2e8263bff11f76b162c7f374174b72d6b2f320ba3e55946d00fc6f21a"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.aarch64-unknown-freebsd.tar.gz"
[[SHTns]]
arch = "i686"
git-tree-sha1 = "a05bdd403863d8379f996a8ee5afffa84250d894"
lazy = true
os = "windows"

    [[SHTns.download]]
    sha256 = "854bc31c9285c416a207c38a90d8cb5b9f48df9fc1862e8f01cda4ee1ebbbf52"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.i686-w64-mingw32.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "efb314ecac942e6edbb44a8621decf853eafbdb1"
lazy = true
os = "windows"

    [[SHTns.download]]
    sha256 = "4b0e72304ec831cff2a860c86a67f9a52cba9a3e8ce61b2a8ca925c332100552"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.7.0+0/SHTns.v3.7.0.x86_64-w64-mingw32.tar.gz"
