[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "6ab5a26f99fe3d724099e19031fb35fc181bacbc"
lazy = true
os = "macos"

    [[SHTns.download]]
    sha256 = "048723dd2ddee391bef57a78d3a0c81270228f7e5cee380d292954d2fb49b3ff"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.aarch64-apple-darwin.tar.gz"
[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "d9482f56bae7d4908ba1e547314d300d242865d3"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "ba3956b8ac2eda7685564089a3373532f67b83b88623666e339cdebab5a76632"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.aarch64-linux-gnu.tar.gz"
[[SHTns]]
arch = "aarch64"
git-tree-sha1 = "810440b91d3eef39f6db35f9af23c27fae375d06"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "32b9596e980b9be2c2f6124eb4c6cf591241347e685bc009c5a72ec5d586cf3c"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.aarch64-linux-musl.tar.gz"
[[SHTns]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9ac0d7b1c34e67b7027897e812b60e174fdacc6"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "265d90df27d0e2bf94446127045036892dd3ce7ef7c2cae631092615e0f5d3d4"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.armv6l-linux-gnueabihf.tar.gz"
[[SHTns]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df6ccfc33fed69bb102a2d495f31f4bf88fd375a"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "de4dd9acc0242b5de1ecd764fc175e3a611498f25ca126da211e0e20f104dd63"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.armv6l-linux-musleabihf.tar.gz"
[[SHTns]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1142f9182dd56a899afc8210653e72d99652425c"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "fa2e33911867d1b8a6bc4533c81ef4ece40660d45ac1dbcd3f64d37fe327b274"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.armv7l-linux-gnueabihf.tar.gz"
[[SHTns]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "053b728cfef1591cfacbdf83415b74f96b416329"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "c5350fb37c6c2f8f56099e55964d7429fbc48e1bbd92590c2c566109940d56ce"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.armv7l-linux-musleabihf.tar.gz"
[[SHTns]]
arch = "i686"
git-tree-sha1 = "a8ff554b41da33fdcbf9333eb2dfea89a019c75b"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "d8e73e0f776df4edc15f59ff20beb79cdfc4615bced30f13b1ff2dbbb710821d"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.i686-linux-gnu.tar.gz"
[[SHTns]]
arch = "i686"
git-tree-sha1 = "b483a2ec9365cb0cd93e6e79823280e0787088f0"
lazy = true
libc = "musl"
os = "linux"

    [[SHTns.download]]
    sha256 = "743d10a1fb3a8c2f4d89b8aeb69cb5ee6fbd77052239a052687bc2a6dcc04986"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.i686-linux-musl.tar.gz"
[[SHTns]]
arch = "i686"
git-tree-sha1 = "8f1daf6e2294cecc268a0294cb175592e3690b70"
lazy = true
os = "windows"

    [[SHTns.download]]
    sha256 = "86539dfdc7d3c308722539ce928710cd17fa6e5791bccfa6ef77e1031daef4b9"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.i686-w64-mingw32.tar.gz"
[[SHTns]]
arch = "powerpc64le"
git-tree-sha1 = "a7b5dbfb418c5fcd953d6636dcfc98e4293f50fa"
lazy = true
libc = "glibc"
os = "linux"

    [[SHTns.download]]
    sha256 = "c77a2a2b511b9674b1605c147166ff6fed1d63df77fcd236d788b425f8206650"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.powerpc64le-linux-gnu.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "edcf6b714eb6dcad7c0c6cc058e0fff01da40e59"
lazy = true
march = "avx"
os = "macos"

    [[SHTns.download]]
    sha256 = "f79eb56ed0a696bf0a07cbbf74ff89f7a21e2f11b9c365e172a7793b4d5cd5f6"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-apple-darwin-march+avx.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "401ad927c0d698f49336050688eee358724028bf"
lazy = true
march = "avx2"
os = "macos"

    [[SHTns.download]]
    sha256 = "77aadb9536d3baa631918373af917bb80dd024e997a0ecdd8a58a6b5a62f098a"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-apple-darwin-march+avx2.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "0caff17ad272453dd647c4c19ae6bf4fb38c512b"
lazy = true
march = "avx512"
os = "macos"

    [[SHTns.download]]
    sha256 = "3edd2c385192bc7e484ccd707575a100c28c556cbcaacbcf5a1f7566157d2cf9"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-apple-darwin-march+avx512.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "bbe6f8970f0d77fbc30366da123d5ae0570a6bea"
lazy = true
march = "x86_64"
os = "macos"

    [[SHTns.download]]
    sha256 = "7d0c64fc92bbb363c7257c33584bbd6ab37373fa26018edb33efd7e34df0ade2"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-apple-darwin-march+x86_64.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "1cc960f7158c40794bd8357af8a7c9f3aa8b882c"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[SHTns.download]]
    sha256 = "cfbc12682416fb69cde74d99da02fc8719bcdf3190bf0ef1f4d24e933c9d269b"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-gnu-march+avx.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "95b47439691af714e6da88cfd6f79a8ba600e5c4"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[SHTns.download]]
    sha256 = "0266bc5ad8ccc132183035018374e27afab1c2b7cd613b8fff87e44d97693a5e"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-gnu-march+avx2.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "baf73a1c3998fa90173c71c090486433c840384d"
lazy = true
libc = "glibc"
march = "avx512"
os = "linux"

    [[SHTns.download]]
    sha256 = "4fd753e1bc538b9d86fbee48b0fc804f3e331de945cfcffd255827bb7d670212"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-gnu-march+avx512.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "ad632081acf8f2e9a2ecf5e27038fc5d12250e64"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[SHTns.download]]
    sha256 = "24633cdcca177433fdb45af19fd030218a26342b2ff19691d7887099eeae205d"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-gnu-march+x86_64.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "db63615e9f1b0837d2b54042c86f2146251e3cd2"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[SHTns.download]]
    sha256 = "9728e014591c7f6ad1100e94c79b655dd6963d71850ad0635bdd41a847e15326"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-musl-march+avx.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "ae91726ffa80d2aaadf4dc514a4488771b9b891e"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[SHTns.download]]
    sha256 = "e7e5ea890e5f70452db3228821e82c87b24be9ba179a18093eac1d851773a902"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-musl-march+avx2.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "2f36ea97442f0c78b8a37e53c84ed06428504795"
lazy = true
libc = "musl"
march = "avx512"
os = "linux"

    [[SHTns.download]]
    sha256 = "0c94730637be01b4b1f3a4db6af3358dd2d401439160eac0fd1d08a01a55a706"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-musl-march+avx512.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "aa201298d06ffde24390668f216eb893b8ab5d5b"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[SHTns.download]]
    sha256 = "173846b2af5c45a50ff33fb6142edb046bf02f9a9c3b3969e2ac0af0af6861f3"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-linux-musl-march+x86_64.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "dad5159ee4c70bb5d386f53d9e4e9e19cb5eb4eb"
lazy = true
march = "avx"
os = "freebsd"

    [[SHTns.download]]
    sha256 = "950219f3ed7f85c2f0f34761ee08d450d03897aaf956c46818a0899fdae147d9"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-unknown-freebsd-march+avx.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "58abe66be88c2cd0052c19d98368855d106f8ce0"
lazy = true
march = "avx2"
os = "freebsd"

    [[SHTns.download]]
    sha256 = "eda113dfe5b9a8f22cd7c7f1b6ea77d6b2e520621758a900371b5953576eac92"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "679066658e735a89e506141c7d8ecc37c15760c6"
lazy = true
march = "avx512"
os = "freebsd"

    [[SHTns.download]]
    sha256 = "9e40cae5053f88fe626ce49d1ba84e013999f6b6ac5777856c9d0f402d6d8b38"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-unknown-freebsd-march+avx512.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "a2535cbb5a60e98f9533bb815a77340681322225"
lazy = true
march = "x86_64"
os = "freebsd"

    [[SHTns.download]]
    sha256 = "5b60682ac266bdf7a3cca9b1ca58e7e21f99609c72da4c94ce233146a2be2d27"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "e42ae142c56c0a63d9a5c9803c96312d6ded05ad"
lazy = true
march = "avx"
os = "windows"

    [[SHTns.download]]
    sha256 = "157f5e2f8605756b0bcf6427c57419bf6e9aa0ae97b69480de871282b81d45e0"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-w64-mingw32-march+avx.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "ec5ca2b586e89010782f0c8676d6fb91a6f51951"
lazy = true
march = "avx2"
os = "windows"

    [[SHTns.download]]
    sha256 = "43cebfe16bc24913a0d15e7adbbdd0b0c7b637e9ee6596bcba225df17139c074"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-w64-mingw32-march+avx2.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "01dec2752dbf516e286c85583102b054bb883511"
lazy = true
march = "avx512"
os = "windows"

    [[SHTns.download]]
    sha256 = "00ebfdf9dd7e845a3b2418a231dc23e1c90bdc92630ff6b6e62edd8861edb823"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-w64-mingw32-march+avx512.tar.gz"
[[SHTns]]
arch = "x86_64"
git-tree-sha1 = "09a052252060113373d97a3724d66fd1b10ae230"
lazy = true
march = "x86_64"
os = "windows"

    [[SHTns.download]]
    sha256 = "a4a82d0882f71cf6edfd693ff84e287cbf66c76de1201434b8fad8f837f120b1"
    url = "https://github.com/JuliaBinaryWrappers/SHTns_jll.jl/releases/download/SHTns-v3.5.2+0/SHTns.v3.5.2.x86_64-w64-mingw32-march+x86_64.tar.gz"
